name: Catapult refrigerator to moon
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DA_WAE: ${{ secrets.THE_KEY_TO_THE_LOCKED_FRIDGE }}
jobs:
  check_skip:
    name: Check if ready for lift-off
    runs-on: ubuntu-latest
    if: |
      !contains(format('{0} {1} {2}', github.event.head_commit.message, github.event.pull_request.title, github.event.pull_request.body), '[skip ci]')
    steps:
      - name: Check if fridge is ready
      - run: |
          cat <<'MESSAGE'
          github.event_name: ${{ toJson(github.event_name) }}
          github.event:
          ${{ toJson(github.event) }}
          MESSAGE
  yeet:
      name: Yeet
      needs: check_skip
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Eat a hot air balloon
          run: |
            curl -L https://fly.io/install.sh | sh
        - name: Catapult fridge and injure man on the moon
          run: |
            /home/runner/.fly/bin/flyctl deploy
