name: Catapult refrigerator to moon
on: [push]
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DA_WAE: ${{ secrets.THE_KEY_TO_THE_LOCKED_FRIDGE }}
jobs:
  yeet:
      name: Yeet
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Eat a hot air balloon
          run: |
            curl -L https://fly.io/install.sh | sh
        - name: Catapult fridge and injure man on the moon
          run: |
            /home/runner/.fly/bin/flyctl deploy
